apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
name: rabbitmq-worker-scaledobject
namespace: default
spec:
scaleTargetRef:
name: my-rabbitmq-worker # Deployment name
minReplicaCount: 1
maxReplicaCount: 10
triggers:
- type: rabbitmq
metadata:
queueName: my-queue
host: RabbitMQConnectionString
queueLength: "50"